import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import SignInModal from "./auth/SignInModal";
import Header from "../components/Header/Header";

const Home: NextPage = () => {
	const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main>
				<p>{hello.data ? hello.data.greeting : "Loading tRPC query..."}</p>

				<Trpc />
			</main>
		</>
	);
};

export default Home;

function Trpc() {
	const nameRef = useRef<HTMLInputElement>(null);
	const [queryValue, setQueryValue] = useState("");
	const greetings = trpc.test.hello.useQuery({
		text: queryValue,
	});

	function textChange(e: ChangeEvent<HTMLInputElement>) {
		e.preventDefault();
		setQueryValue(e.target.value);
	}

	return (
		<div>
			<input ref={nameRef} onChange={(e) => textChange(e)} type="text" />
			{greetings.data ? greetings.data.greeting : ""}
		</div>
	);
}
